apiVersion: v1
kind: Service
metadata:
  name: insignia-express-service
  labels:
    app: insignia-express
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: insignia-express
