name: "Build and Deploy to GKE"

on:
  push:

env:
  PROJECT_ID: "${{ secrets.GCP_PROJECT_ID }}" # TODO: update to your Google Cloud project ID
  GAR_LOCATION: "asia-southeast2" # TODO: update to your region
  GKE_CLUSTER: "insignia-cluster" # TODO: update to your cluster name
  GKE_ZONE: "us-central1" # TODO: update to your cluster zone
  DEPLOYMENT_NAME: "insignia-express" # TODO: update to your deployment name
  SERVICE_KEY: "${{ secrets.GCP_SERVICE_KEY }}"
  REPOSITORY: "insignia-test" # TODO: update to your Artifact Registry docker repository name

jobs:
  setup-build-publish-deploy:
    name: "Setup, Build, Publish, and Deploy"
    runs-on: "ubuntu-latest"
    environment: "production"

    permissions:
      contents: "read"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_KEY }}"

      - name: "Docker Auth"
        uses: "docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567" # docker/login-action@v3
        with:
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          username: "_json_key"
          password: "${{ secrets.GCP_SERVICE_KEY }}"

      - name: "Set up GKE credentials"
        uses: "google-github-actions/get-gke-credentials@6051de21ad50fbb1767bc93c11357a49082ad116" # google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          location: "${{ env.GKE_ZONE }}"
          credentials: "${{ secrets.GCP_SERVICE_KEY }}"

      - name: "Build and push Docker container"
        run: |-
          IMAGE_NAME="insignia-express" # TODO: update to your Docker image name
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}"

          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push "${DOCKER_TAG}"

      - name: "Deploy to GKE"
        run: |-
          IMAGE_NAME="insignia-express" # TODO: update to your Docker image name
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}"

          # Replace the image name in the deployment manifest
          sed -i "s|LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG|${DOCKER_TAG}|g" k8s/deployment.yaml

          # Apply the Kubernetes manifests
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
